---
title: "NYC weather in 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    theme:
      version: 5
      bg: "#101010"
      fg: "white" 
      primary: "white"
      navbar-bg: "steelblue"
      base_font: Lato
      heading_font:
        google: Lato
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("ny_noaa")
ny_noaa = tibble(ny_noaa)

ny_noaa_avg = 
  ny_noaa %>% 
  drop_na(prcp, snow, snwd, tmax, tmin) %>% 
  mutate(
    prcp = as.numeric(prcp),
    snow = as.numeric(snow),
    snwd = as.numeric(snwd),
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin)
    ) %>% 
  group_by(date) %>% 
  summarize(prcp = mean(prcp),
            snow = mean(snow),
            snwd = mean(snwd),
            tmax = mean(tmax),
            tmin = mean(tmin))

ny_noaa_avg = 
  ny_noaa_avg %>% 
  mutate(
    year = as.integer(strftime(date, "%Y")),
    weekday = as.integer(strftime(date, "%u")),
    month = as.integer(strftime(date, "%m")),
    week = as.integer(strftime(date, "%W")),
    day = as.integer(strftime(date, "%d"))
    ) %>% 
  mutate(
    weekday = factor(weekday, levels = 1:7, 
                     labels = c("Mon", "Tue", "Wed", "Thr", "Fri", "Sat", "Sun"), 
                     ordered = TRUE),
    month = factor(month, levels = 1:12, labels = month.abb, ordered = TRUE)
  ) %>% 
  group_by(month) %>% 
  mutate(monthweek = 1 + week - min(week))
```

Row {data-height=350}
-----------------------------------------------------------------------

### 2009 NYC daily precipitation and snowfall

```{r}
ny_noaa_avg %>%  
  filter(year == 2009) %>%
  mutate(date = as.Date(date)) %>% 
  plot_ly(x = ~date) %>% 
  add_lines(y = ~prcp, name = "precipitation") %>% 
  add_lines(y = ~snow, name = "snowfall") %>% 
  layout(
    title = "2009 NYC daily precipitation and snowfall",
    xaxis = list(rangeslider = list(type = "date")),
    yaxis = list(title = "unit: mm"))
```

Row {data-height=650}
-----------------------------------------------------------------------

### 2009 NYC Precipitation Calendar

```{r}
prcp_2009 = 
  ny_noaa_avg %>% 
  filter(year == 2009) %>% 
  ggplot(aes(weekday, monthweek, fill = prcp)) + 
  geom_tile(color = "white") + 
  geom_text(aes(label = day), size = 3) + 
  scale_fill_gradient2(low = "grey95",  
                       high = "steelblue4") +
  facet_wrap(~month, nrow = 3) + 
  scale_y_reverse(name = "Week of the month") + 
  xlab("Day") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 30, 
                                   hjust = 1, vjust = 1))

ggplotly(prcp_2009)
```


### 2009 NYC daily temperature, snow depth & snow melted amount

```{r fig.width=5, fig.height=5}
fig =
  ny_noaa_avg %>% 
  filter(year == 2009) %>% 
  mutate(nextday = date + 1,
         year = as.character(year)) %>% 
  left_join(ny_noaa_avg, by = c("nextday" = "date")) %>% 
  mutate(tmean = (tmax.x + tmin.x)/2,
         snmlt = snwd.x + snow.y - snwd.y) %>% 
  filter(snwd.x != 0) %>% 
  plot_ly(x = ~tmax.y, y = ~snwd.x, z = ~snmlt, 
          color = ~month.x, 
          colors = c("#4AC6B7", "#1972A4", "#965F8A", "#FF7070", "#C61951")) %>% 
  add_markers() %>% 
  layout(
    scene = list(
      xaxis = list(title = "maximum temperature (F)"),
      yaxis = list(title = "snow depth (mm)"),
      zaxis = list(title = "snow melted (mm)"))
  )

fig
```



